### ISSUE TITLE
Tests leave hanging containers if the process is exited prematurely

### ISSUE THREAD

**Issue by ajwootto** [Trendyol/jest-testcontainers#15]
If the Jest process running the tests is exited prematurely (eg. by ctrl+c user interrupt ) then the docker containers spun up by this preset will continue running and require manual shutdown.

Is there any way for the preset to "attach" the containers to the process in some way so that they will automatically exit when the process itself exits?

**Comment by Yengas** [comment]
Hey Adam,

Thanks for reporting this. I've upgraded testcontainers to a later version. It should fix this. Written down the details on how it fixes this in #16 if you are interested.

Published a new version `1.4.0`. Please use this version and check if you are having the same issue. Feel free to close this issue if everything is ok.

Regards,
Yigitcan

**Comment by ajwootto** [comment]
Hi, this seems to fix this issue. Thanks!
