### ISSUE TITLE
add example with postgresql and migration

### ISSUE THREAD

**Issue by Yengas** [Trendyol/jest-testcontainers#20]
we can create an example that showcases how to write integration tests for postgresql.

[node-pg-migrate](https://www.npmjs.com/package/node-pg-migrate) or something else, can be used to manage migrations. should support watch mode.

**Comment by RipTheJacker** [comment]
I am trying to fix in a fork but still cannot get postgres to work with this. The image seems to time out every attempt at running.In my fork, I updated testcontainers-node and modified the config to allow waiting for health checks. I am not sure what is happening or why it times out.

**Comment by Yengas** [comment]
Hey @RipTheJacker,

Can you please link me to your branch that does not work. We currently use this library in multiple projects for PostgreSQL integration testing. I will try to publish a working example this weekend, so you can use it as a reference.

Cheers,
Yengas

**Comment by Yengas** [comment]
Hey @RipTheJacker,

Just published [an example project](https://github.com/Yengas/nodejs-postgresql-testcontainers) showcasing how to write integration tests for PostgreSQL. It uses [node-pg-migrate](https://github.com/salsita/node-pg-migrate) for the DB migration. It also has CI integration for Github + Gitlab. Tried to keep the example as simple as possible.

You can also check [this commit](https://github.com/Yengas/nodejs-postgresql-testcontainers/commit/c8a9920ba90ac33051a33cd5eea082448caaa132) where I add jest-testcontainers to the project.

LMK if you have any more questions or problems integrating this into your project.

Cheers,
Yengas
